djangotutorial/mydiaryproject/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls'))     # 追加：includeメソッドでurl設定を追加
]

djangotutorial/mydiaryproject/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('diary/create/', views.DiaryCreateView.as_view(), name='diary_create'),
    path('diary/create/complete/', views.DiaryCreateComplete.as_view(), name='diary_create_complete'),
]

djangotutorial/mydiaryproject/diary/models.py
from django.db import models
from django.utils import timezone
import uuid

# Create your models here.


class Diary(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=Flase)
    date = models.DateField(verbose_name='日付', default=timezone.now)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    text = models.CharField(verbose_name='本文', max_length=200)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    update_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)

djangotutorial/mydiaryproject/diary/forms.py
from django import forms
from .models import Diary

class DiaryForm(forms.ModelForm) :
    class Meta:
        model = Diary
        fields = ('date', 'title', 'text', )

djangotutorial/mydiaryproject/diary/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class IndexView(TemplateView) :
    template_name = "index.html"


class DiaryCreateView(CreateVirew):
    template_name = 'diary_create.html'
    form_class = DiaryForm
    success_url = reverse_lazy('diary:diary_create_complete')


class DiaryCreateComplete(TemplateView):
    template_name = 'diary_create_complete.html'

djangotutorial/mydiaryproject/templates/diary_create.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MyDiaryApp</title>
</head>

<body>

  <form action="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">投稿</button>
  </form>

</body>

</html>

djangotutorial/mydiaryproject/templates/diary_create_complete.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MyDiaryApp</title>
</head>

<body>
  <p>日記の投稿が完了しました！</p>
  <a href="{% url 'diary:index' %}">トップへ戻る</a>
</body>

</html>

djangotutorial/mydiaryproject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MyDiaryApp</title>
</head>
<body>
  <h1>Diary App by Django</h1>
</body>
</html>